version: '2.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.15
    container_name: es01
    environment:
      name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./data01:/usr/share/elasticsearch/data
