version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - "5601:5601"
    networks:
      - elastic
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://127.0.0.1:9200
      ELASTICSEARCH_URL: http://127.0.0.1:9200
networks:
  elastic:
    driver: bridge