version: "3.1"  #这个版本和宿主机docker-compose版本相关
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    restart: always
    networks:
      - elastic
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=database
      - MYSQL_MASTER_SERVICE_HOST=database
      - MYSQL_DATABASE_NUM=1
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_PORT=8926
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=c1234567


networks:
  elastic:
    driver: bridge