version: '3'

services:
  nacos:
    image: nacos/nacos-server:1.3.2
    container_name: nacos
    restart: always
    environment:
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MODE: standalone
      MYSQL_SERVICE_HOST: server.anymre.top
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 8926
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: c1234567
      NACOS_APPLICATION_PORT: 8848
      JVM_XMS: 512m
      JVM_MMS: 320m
    ports:
      - "8848:8848"
    mem_limit: 600m
