version: "3.1"
services:
  database:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=1000
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server_id=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c1234567
      JAVA_OPTS: -Xms100m -Xmx512m"
    networks:
      - mysql

    ports:
      - '8926:3306'
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf:/etc/mysql/conf.d"

networks:
  mysql:
    driver: bridge