version: "3.1"
services:
  database:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=1000
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c1234567
    networks:
      - elastic

    ports:
      - '8926:3306'
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf:/etc/mysql/conf.d"

networks:
  mysql:
    driver: bridge