version: "2"
services:
  nginx:
    image: nginx
    privileged: true
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./www/conf/:/etc/nginx/
      - ./www/logs:/var/log/nginx
    networks:
      - web-net
  php:
    image: phpdockerio/php72-fpm
    privileged: true
    volumes:
      - ./www:/web
    networks:
      - web-net
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - web-net

networks:
  web-net: