version: "2"
services:
  nginx:
    image: nginx
    privileged: true
    ports:
      - "80:80"
    volumes:
      - /www:/usr/share/nginx/html
      - /www/conf/nginx.conf:/etc/nginx/nginx.conf
      - /www/logs:/var/log/nginx
    networks:
      - web-net
  php:
    image: phpdockerio/php72-fpm
    privileged: true
    volumes:
      - /www:/web
    networks:
      - web-net
networks:
  web-net: