version: '3'

services:
  pulsar:
    image: apachepulsar/pulsar:2.8.0
    ports:
      - 8086:8080
      - 6650:6650
#    volumes:
#      - pulsardata:/pulsar/data
#      - pulsarconf:/pulsar/conf
    command:
      bin/pulsar standalone
#volumes:
#  pulsardata: {}
#  pulsarconf: {}
